// <auto-generated />
using DemoNNS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoNNS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230724102335_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("DemoNNS.Models.Student", b =>
                {
                    b.Property<string>("StrudentID")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrudentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("StrudentID");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
